catapi:
  base-url: https://api.thecatapi.com/v1
  api-key: ${CAT_API_KEY:}
dogapi:
  base-url: https://api.thedogapi.com/v1
  api-key: ${DOG_API_KEY:}
spring:
  main:
    web-application-type: servlet
  
  datasource:
    url: jdbc:postgresql://localhost:5432/dailycat
    username: dailycat
    password: dailycat123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true